---
title: Video Streaming Architecture
---
flowchart TB
    user --- ui
    ui --- api-gateway
    ui -- presignedURL --- video-streaming
    ui -- presignedURL --- video-upload
    api-gateway --- auth0
    api-gateway  --- presigned-url-generator
    presigned-url-generator --- s3
    transcoder --- s3
    video-streaming --- s3
    video-upload --- transcoder
    presigned-url-generator --- MongoDB:videos
    transcoder --- MongoDB:videos
    video-upload --- MongoDB:videos
    video-streaming --- MongoDB:videos