version: '3'
services:
  db:
    image: mongo:7.0.0
    container_name: db
    ports:
      - "4000:27017"
    restart: always

  azure-storage:
    #    image: azure-storage
    build:
      context: ./azure-storage
      dockerfile: Dockerfile-prod
    container_name: video-storage
    ports:
      - "4001:80"
    environment:
      - PORT=80
      - STORAGE_ACCOUNT_NAME=${STORAGE_ACCOUNT_NAME}
      - STORAGE_ACCESS_KEY=${STORAGE_ACCESS_KEY}
      - CONTAINER_NAME=${CONTAINER_NAME}
    restart: always

  history:
    #    image: history
    build:
      context: ./history
      dockerfile: Dockerfile-prod
    container_name: history
    ports:
      - "4002:80"
    environment:
      - PORT=80
    restart: always

  video-streaming:
    image: video-streaming
    build:
      context: ./video-streaming
      dockerfile: Dockerfile-prod
    container_name: video-streaming
    ports:
      - "4003:80"
    environment:
      - PORT=80
      - DBNAME=video-streaming
      - VIDEO_STORAGE_HOST=video-storage
      - VIDEO_STORAGE_PORT=80
    depends_on:
      - db
    restart: always