FROM amazoncorretto:17
LABEL authors="baddog"

WORKDIR /app/azure-storage
COPY . /app/azure-storage

EXPOSE 4001

# Fetch project dependencies
RUN chmod +x start.sh && ./gradlew getDependencies

# script which watches source file changes in background and executes bootRun
CMD ["bash", "start.sh"]