FROM amazoncorretto:17
LABEL authors="baddog"

WORKDIR /app/history
COPY . /app/history

EXPOSE 4002

# Fetch project dependencies
RUN chmod +x ./scripts/start.sh && ./gradlew getDependencies

# script which watches source file changes in background and executes bootRun
CMD ["bash", "./scripts/start.sh"]