FROM amazoncorretto:17
LABEL authors="baddog"

WORKDIR /app/aws-simple-storage-service
COPY . /app/aws-simple-storage-service

EXPOSE 4001

# Fetch project dependencies
RUN chmod +x ./scripts/start.sh && ./gradlew getDependencies

# script which watches source file changes in background and executes bootRun
CMD ["bash", "./scripts/start.sh"]