AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  s3-presigned-url-generator
  Sample SAM Template for s3-presigned-url-generator
Globals:
  Function:
    Timeout: 5
    MemorySize: 128
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true
Resources:
  PresignedUrlGenerator:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: src/main/
      Handler: bootstrap
      Runtime: provided.al2023
      Architectures:
        - x86_64
      Events:
        GetUrl:
          Type: Api
          Properties:
            Path: /s3-presigned-url-generator
            Method: GET
        PutUrl:
          Type: Api
          Properties:
            Path: /s3-presigned-url-generator
            Method: PUT
        DeleteUrl:
          Type: Api
          Properties:
            Path: /s3-presigned-url-generator
            Method: DELETE
      Environment:
        Variables:
          PARAM1: VALUE
  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
Outputs:
  S3PresignedUrlAPI:
    Description: API Gateway endpoint URL for Prod environment for s3-presigned-url-generator functions
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/s3-presigned-url-generator/"
  S3PresignedUrlFunction:
    Description: s3-presigned-url-generator ARN
    Value: !GetAtt PresignedUrlGenerator.Arn
  S3PresignedUrlFunctionIamRole:
    Description: IAM Role created for s3-presigned-url-generator functions
    Value: !GetAtt PresignedUrlGenerator.Arn
