apiVersion: v1
kind: Secret
metadata:
  name: aws-simple-storage-service-secret
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QUtJQVlLQUtUVlVRUzRYUTdCTFY=
  AWS_SECRET_KEY: WFJsRXlTRThudzYram1wQUdleUxOVFFlZkV3ZGxzK0ZkTFdoa0dLTA==
