FROM amazoncorretto:17
LABEL authors="baddog"

WORKDIR /app/video-streaming
COPY . /app/video-streaming

EXPOSE 4003

# Fetch project dependencies
RUN chmod +x ./scripts/start.sh && ./gradlew getDependencies

# script which watches source file changes in background and executes bootRun
CMD ["bash", "start.sh"]