name: Delete microservice

on:
  # Allow delete to be invoked manually through the GitHub Actions user interface
  workflow_dispatch:

jobs:
  delete:
    runs-on: ubuntu-latest

    # Set environment variables
    # TODO: remove unused environment variables
    env:
      VERSION: ${{ secrets.AZURE_STORAGE_VERSION }}
      CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
      REGISTRY_UN: ${{ secrets.REGISTRY_UN }}
      REGISTRY_PW: ${{ secrets.REGISTRY_PW }}
      STORAGE_ACCOUNT_NAME: ${{ secrets.STORAGE_ACCOUNT_NAME }}
      STORAGE_ACCESS_KEY: ${{ secrets.STORAGE_ACCESS_KEY }}
      CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
      PORT: ${{ secrets.PORT }}

    steps:
      # Check out repo
      - uses: actions/checkout@v4

      # Setup JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Install Kubectl and connect to the cluster
      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}
          kubectl-version: v1.29.1

      # Delete the cluster
      - name: Delete
        run: ./azure-storage/scripts/delete.sh